// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZrt5kKFx3zJDPY7wITkXqQrYecWdMiJk',
    appId: '1:651667824143:web:42e8971292b08190798d7a',
    messagingSenderId: '651667824143',
    projectId: 'asistenciaupeu-94fbe',
    authDomain: 'asistenciaupeu-94fbe.firebaseapp.com',
    storageBucket: 'asistenciaupeu-94fbe.firebasestorage.app',
    measurementId: 'G-5Q3KQ3VF3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4WZ35eb-VsUGfx9n0ixCDf-xgie_b_cs',
    appId: '1:651667824143:android:2785e1427509869a798d7a',
    messagingSenderId: '651667824143',
    projectId: 'asistenciaupeu-94fbe',
    storageBucket: 'asistenciaupeu-94fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ5sDI_8wGSld-oguJhmpO1d6iAGJ9734',
    appId: '1:651667824143:ios:37e8cdc8479887e9798d7a',
    messagingSenderId: '651667824143',
    projectId: 'asistenciaupeu-94fbe',
    storageBucket: 'asistenciaupeu-94fbe.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.asistenciaUpeu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ5sDI_8wGSld-oguJhmpO1d6iAGJ9734',
    appId: '1:651667824143:ios:37e8cdc8479887e9798d7a',
    messagingSenderId: '651667824143',
    projectId: 'asistenciaupeu-94fbe',
    storageBucket: 'asistenciaupeu-94fbe.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.asistenciaUpeu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZrt5kKFx3zJDPY7wITkXqQrYecWdMiJk',
    appId: '1:651667824143:web:f088bbacdc077697798d7a',
    messagingSenderId: '651667824143',
    projectId: 'asistenciaupeu-94fbe',
    authDomain: 'asistenciaupeu-94fbe.firebaseapp.com',
    storageBucket: 'asistenciaupeu-94fbe.firebasestorage.app',
    measurementId: 'G-NVEEN4HPB8',
  );
}
